nacos:
  namespace: 6edc4d5b-d911-46f5-82e4-70e03f504073
  server-addr-local: localhost:8848

spring:
  # 应用名称
  application:
    name: api-limit
  # nacos配置
  cloud:
    nacos:
      # 注册中心
      discovery:
        # 服务注册地址 (nacos服务接口,不能加http前缀，直接访问localhost:8848/nacos可以进入管理页面) 可以配置多个，逗号分隔
        server-addr: ${nacos.server-addr-local}
        # nacos配置文件的命名空间(命名空间ID，Nacos通过不同的命名空间来区分不同的环境，进行数据隔离,服务消费时只能消费到对应命名空间下的服务)
        namespace: ${nacos.namespace}
        # 是否开启Nacos Watch，默认true(类似长连接监听服务端信息变化的功能)
        watch:
          enabled: false
      config:
        server-addr: ${nacos.server-addr-local}
        namespace: ${nacos.namespace}
        prefix: ${spring.application.name}
        group: DEFAULT_GROUP
        # 配置文件的格式，默认为properties
        file-extension: yml
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
    timeout: 60000
    block-when-exhausted: true
    jedis:
      pool:
        ##连接池最大连接数（使用负值表示没有限制）默认0
        max-active: 1024
        ##连接池最大阻塞等待时间 （使用负值表示没有限制） 默认-1
        max-wait: 60000
        ##连接池中的最大空闲连接 默认8
        max-idle: 200
        ##连接池中的最小空闲连接 默认0
        min-idle: 200

